# Плагин предназначен для выдачи доната на разных серверах
# Например, игроку на сервере Auth выдается донат, который должен работать на сервере Survival.
# Или же, на сервере Survival выдается донат, который должен работать на сервере Auth
# Плагин ставится отдельно на каждый сервер и связывается БД (MySQL)

# Настройки подключения к базе данных
database:
  type: MYSQL
  hostname: 127.0.0.1
  port: 3306
  database: syncdonate
  username: root
  password: ""

# Название текущего сервера, на котором стоит плагин
serverName: auth

# Идентификаторы, по которым будет осуществляться выдача доната.
# На каждом сервере могут быть разные команды и предметы в меню для разных идентификаторов
identifiers:
  # Цифра через которую выдача будет происходить, проще говоря - идентификатор
  1:
    # Иконка в меню, которое открывается при команде /donatecarts
    itemstack:
      type: STONE
      amount: 1
      display: "&7Камень"
      lore:
        - "&eЭтот предмет выдаст вам камень!"
      customModelData: 1
    # Команда, которая будет выполняться при выдаче.
    command: "/give %player% stone 1"
  # Цифра через которую выдача будет происходить, проще говоря - идентификатор
  2:
    # Иконка в меню, которое открывается при команде /donatecarts
    itemstack:
      type: DIAMOND
      amount: 1
      display: "&7Привилегия ВИП"
      lore:
        - "&eВыдаст вам ВИП"
    # Команда, которая будет выполняться при выдаче.
    command: "/lp user %player% parent set vip"

# Настройки меню с карточками
cartMenu:
  # Название меню
  title: "Карточки"

  # Настройки расположения предметов
  pattern:
    - "aaaaaaaaa"
    - "aaaaaaaaa"
    - "aaaaaaaaa"
    - "aaaaaaaaa"
    - "bbbbbbbbb"
    - "--------c"

  items:
    a:
      click: CART
    b:
      item:
        type: GREEN_STAINED_GLASS_PANE
        display: "&cКарточки"
      click: NONE
    c:
      item:
        type: DIAMOND
        display: "&cЧто это такое?"
        lore:
          - "&fЭто весь Ваш купленный донат,"
          - "&fкоторый вы можете получить просто кликнув по предмету"
      click: NONE
